package main

import (
	"math/rand"
	"time"
)

var commonCookie = "__cmpcc=1; __cmpconsentx17155=CP9AEggP9AEggAfSDBRUAwEgAAAAAEPAAAYgAABBQgJgA4AM-AjwBKoDfAHbAO5AgoBIgCSgEowJaATHAmSBNICfYFBAKDhBQAAA; __cmpcccx17155=aBP9ASYwAAgAzA_gACAAcABgAHgAUABgADgAJwAXABgAD0AIQAiABQADEAGgAQQAmgBeAD2AIcATIAxABlgEFAIWARIAjoBOACeAFPAKuAWYA0IBzAEYgI7gUaBRwCpwG6AN2Ab6BBkCFgENgIkgSlAlmBMACZYFdwLAgWZAuCBcMDHYGPwMjAZ4A68CIgEl4JdATBAm_BRoCoAFRwAoXVQvihlZDpmrIEA;"
var jwtCookie = ""
var cookie = ""

type Target struct {
	X          int
	Y          int
	TroopsType int
	Count      int
}

const LEGIONER = 1
const CAESARIS = 5

const LEGIONER_SQUAD_SIZE = 2
const CAESARIS_SQUAD_SIZE = 2

var legionerTargets = []Target{
	{13, 57, LEGIONER, LEGIONER_SQUAD_SIZE},
	{15, 57, LEGIONER, LEGIONER_SQUAD_SIZE},
	{11, 56, LEGIONER, LEGIONER_SQUAD_SIZE},
	{13, 56, LEGIONER, LEGIONER_SQUAD_SIZE},
	{9, 55, LEGIONER, LEGIONER_SQUAD_SIZE},
	{15, 54, LEGIONER, LEGIONER_SQUAD_SIZE},
	{9, 53, LEGIONER, LEGIONER_SQUAD_SIZE},
	{10, 53, LEGIONER, LEGIONER_SQUAD_SIZE},
	{12, 52, LEGIONER, LEGIONER_SQUAD_SIZE},
	{19, 54, LEGIONER, LEGIONER_SQUAD_SIZE},
	{15, 49, LEGIONER, LEGIONER_SQUAD_SIZE},
	{7, 56, LEGIONER, LEGIONER_SQUAD_SIZE},
	{5, 60, CAESARIS, CAESARIS_SQUAD_SIZE},
	{11, 60, CAESARIS, CAESARIS_SQUAD_SIZE},
	{18, 61, CAESARIS, CAESARIS_SQUAD_SIZE},
	{20, 61, CAESARIS, CAESARIS_SQUAD_SIZE},
	{9, 59, CAESARIS, CAESARIS_SQUAD_SIZE},
}

var caesarisTargets = []Target{
	// 4-21 NA 49-61
	{14, 58, CAESARIS, CAESARIS_SQUAD_SIZE},
	{4, 56, CAESARIS, CAESARIS_SQUAD_SIZE},
	{6, 56, CAESARIS, CAESARIS_SQUAD_SIZE},
	{21, 55, CAESARIS, CAESARIS_SQUAD_SIZE},
	{4, 55, CAESARIS, CAESARIS_SQUAD_SIZE},
	{9, 49, CAESARIS, CAESARIS_SQUAD_SIZE},
	{9, 48, CAESARIS, CAESARIS_SQUAD_SIZE},
	{10, 48, CAESARIS, CAESARIS_SQUAD_SIZE},
	{10, 46, CAESARIS, CAESARIS_SQUAD_SIZE},
	{6, 49, CAESARIS, CAESARIS_SQUAD_SIZE},

	//
	{19, 47, CAESARIS, CAESARIS_SQUAD_SIZE},
	{16, 48, CAESARIS, CAESARIS_SQUAD_SIZE},
	{3, 55, CAESARIS, CAESARIS_SQUAD_SIZE},
	{2, 51, CAESARIS, CAESARIS_SQUAD_SIZE},
	{4, 62, CAESARIS, CAESARIS_SQUAD_SIZE},
	{8, 66, CAESARIS, CAESARIS_SQUAD_SIZE},
	{7, 67, CAESARIS, CAESARIS_SQUAD_SIZE},
	{10, 66, CAESARIS, CAESARIS_SQUAD_SIZE},
	{11, 65, CAESARIS, CAESARIS_SQUAD_SIZE},
	{12, 65, CAESARIS, CAESARIS_SQUAD_SIZE},
	{16, 65, CAESARIS, CAESARIS_SQUAD_SIZE},
	{19, 62, CAESARIS, CAESARIS_SQUAD_SIZE},
	{25, 60, CAESARIS, CAESARIS_SQUAD_SIZE},
	{28, 60, CAESARIS, CAESARIS_SQUAD_SIZE},
	{28, 59, CAESARIS, CAESARIS_SQUAD_SIZE},
	{29, 59, CAESARIS, CAESARIS_SQUAD_SIZE},
	{28, 57, CAESARIS, CAESARIS_SQUAD_SIZE},
	{26, 53, CAESARIS, CAESARIS_SQUAD_SIZE},
	{24, 53, CAESARIS, CAESARIS_SQUAD_SIZE},
	{29, 51, CAESARIS, CAESARIS_SQUAD_SIZE},

	// REMOVED BY LEGS
	//{13, 57, CAESARIS, CAESARIS_SQUAD_SIZE},
	//{15, 57, CAESARIS, CAESARIS_SQUAD_SIZE},
	//{7, 56, CAESARIS, CAESARIS_SQUAD_SIZE},
	//{11, 56, CAESARIS, CAESARIS_SQUAD_SIZE},
	//{13, 56, CAESARIS, CAESARIS_SQUAD_SIZE},
	//{9, 55, CAESARIS, CAESARIS_SQUAD_SIZE},
	//{15, 54, CAESARIS, CAESARIS_SQUAD_SIZE},
	//{19, 54, CAESARIS, CAESARIS_SQUAD_SIZE},
	//{10, 53, CAESARIS, CAESARIS_SQUAD_SIZE},
	//{9, 53, CAESARIS, CAESARIS_SQUAD_SIZE},
	//{12, 52, CAESARIS, CAESARIS_SQUAD_SIZE},
	//{15, 49, CAESARIS, CAESARIS_SQUAD_SIZE},

	//{5, 60, CAESARIS, CAESARIS_SQUAD_SIZE},
	//{11, 60, CAESARIS, CAESARIS_SQUAD_SIZE},
	//{18, 61, CAESARIS, CAESARIS_SQUAD_SIZE},
	//{20, 61, CAESARIS, CAESARIS_SQUAD_SIZE},
	//{9, 59, CAESARIS, CAESARIS_SQUAD_SIZE},
}

const username = "777McTRAXER777"
const password = "qwe123"
const villageId = 18469

func main() {
	Login(username, password)

	go SendTroops(caesarisTargets, "Caesaris")
	time.Sleep(time.Second * (60 + time.Duration(rand.Intn(120))))
	go SendTroops(legionerTargets, "Legs")

	for {
		time.Sleep(time.Minute * 100)
	}
}
